spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.exmail.qq.com}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      "[mail.smtp.socketFactory.class]": javax.net.ssl.SSLSocketFactory
      "[mail.smtp.socketFactory.fallback]": false
      "[mail.smtp.socketFactory.port]": 465
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000

mail:
  from: ${SPRING_MAIL_USERNAME}
  personal: R哥
  bcc: ${SPRING_MAIL_BCC:}
  subject: Spring Boot 发邮件测试主题