server:
  port: 8080
  netty:
    connection-timeout: 3s
    max-keep-alive-requests: 100
    idle-timeout: 30s

spring:
  webflux:
    static-path-pattern: /**
    problemdetails:
      enabled: true