server:
  port: 8088

spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.exmail.qq.com}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      "[mail.smtp.socketFactory.class]": javax.net.ssl.SSLSocketFactory
      "[mail.smtp.socketFactory.fallback]": false
      "[mail.smtp.socketFactory.port]": 465
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
  boot:
    admin:
      notify:
        mail:
          enabled: false
          from: Spring Boot Admin <${SPRING_MAIL_USERNAME}>
          to: ${SPRING_BOOT_ADMIN_NOTIFY_TO_EMAIL} # 多个以,分隔
          cc: ${SPRING_BOOT_ADMIN_NOTIFY_CC_EMAIL} # 多个以,分隔
        dingtalk:
          enabled: true
          webhook-url: ${DING_TALK_WEBHOOK_URL} # 必填，钉钉机器人Webhook地址
          secret: ${DING_TALK_SECRET:} # 可选，安全设置加签秘钥
          message: "应用警报：应用 #{name} - #{id} 掉线了！！！"